// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/voicinne-home/ChallengeFlow.tsx": () => import("../components/mockups/voicinne-home/ChallengeFlow.tsx"),
  "./components/mockups/voicinne-home/CinematicMinimal.tsx": () => import("../components/mockups/voicinne-home/CinematicMinimal.tsx"),
  "./components/mockups/voicinne-home/ClassifiedIntel.tsx": () => import("../components/mockups/voicinne-home/ClassifiedIntel.tsx"),
  "./components/mockups/voicinne-home/TheStatLead.tsx": () => import("../components/mockups/voicinne-home/TheStatLead.tsx")
};
