import { Router } from "express";
import { GoogleGenAI } from "@google/genai";
import { logger } from "../../lib/logger";

const router = Router();

const PERSONA_PROMPT = `You are generating a psychological debriefing persona. The user provided these facts about their relationship. Generate a JSON config for a Voice Agent. It must include a \`reveal_message\` that validates the user's relative (Do not shame them), explains how the deepfake was made (44 seconds of audio), warns about scammers, and proposes a family passcode.

Respond with ONLY valid JSON. Example shape:
{
  "tone": "warm",
  "relationship": "close_family",
  "vocabulary": "casual",
  "emotionalTriggers": ["trust", "familiarity"],
  "systemInstruction": "...",
  "reveal_message": "..."
}`;

router.post("/generate-persona", async (req, res) => {
  const { transcription } = req.body as { transcription?: string };
  logger.info(
    { transcriptionLength: transcription?.length ?? 0 },
    "[voicinne] POST /api/generate-persona received"
  );

  if (!transcription) {
    res.status(400).json({ error: "transcription is required" });
    return;
  }

  const apiKey = process.env.GEMINI_API_KEY;
  if (!apiKey) {
    res.status(500).json({ error: "GEMINI_API_KEY not configured" });
    return;
  }

  try {
    const ai = new GoogleGenAI({ apiKey });

    const response = await ai.models.generateContent({
      model: "gemini-2.5-pro",
      contents: `${PERSONA_PROMPT}\n\nUser relationship facts:\n${transcription}`,
      config: {
        responseMimeType: "application/json",
      },
    });

    const raw = response.text ?? "{}";
    let persona: unknown;
    try {
      persona = JSON.parse(raw);
    } catch {
      persona = { raw };
    }

    logger.info("[voicinne] persona generated by Gemini");
    res.json({ persona });
  } catch (err) {
    const message = err instanceof Error ? err.message : String(err);
    logger.error({ err }, "[voicinne] generate-persona failed");
    res.status(502).json({ error: "Persona generation failed", details: message });
  }
});

export default router;
